### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by mnaamani**
Apply GPLv3 License

### CODE REVIEW

**Comment by bwhm** [comment]
@mnaamani 
1. Looks good to me, but maybe also have License file showing in the repo header?
2. Trying to get an approval/disapproval from the substrate team.

**Comment by mnaamani** [comment]
I think github will detect the LICENSE file and display the header automatically when its merged.

**Comment by mnaamani** [comment]
Did we get a final response on this from substrate team?

**Comment by bwhm** [comment]
> Did we get a final response on this from substrate team?

From the discussion on their riot chat and what I have been able to find [myself](https://www.apache.org/licenses/GPL-compatibility.html), it's no problem for us to pull from them. They will not be able to pull (at least directly?) from us.

**Pull request merged**
