### PR TITLE
Improve error message on missing runtime directory

### PR DESCRIPTION
**Pull request by dagurval**

### CODE REVIEW

**Comment by dagurval** [comment]
Before:
```
$ ./build-runtime.sh
/home/dagurval/substrate-node-joystream
Building webassembly binary in substrate-runtime-joystream/...
./build-runtime.sh: line 19: cd: /home/dagurval/substrate-node-joystream/substrate-runtime-joystream/: No such file or directory
```

After:
```
$ ./build-runtime.sh
The 'substrate-runtime-joystream' directory is missing. Did you git clone it yet?
```

**Comment by jfinkhaeuser** [comment]
Nice!

It's also possible to clone elsewhere and create a symbolic link. Maybe modify the message to say `Did you git clone or symlink it yet?` - just to give people the hint?

**Comment by dagurval** [comment]
> It's also possible to clone elsewhere and create a symbolic link. Maybe modify the message to say `Did you git clone or symlink it yet?` - just to give people the hint?

Sure, updated with your suggested change

**Comment by jfinkhaeuser** [comment]
Thanks!

I'd be happy to merge, but let's let @mnaamani review.

**Comment by mnaamani** [comment]
Looks good, thanks for adding this.

**Pull request merged**
