### PR TITLE
Add Dockerfile. Fixes #60

### LINKED ISSUE #60: Compile Docker image
As discussed on the Telegram channel (I'm S J) I'll be trying to compile the node into a docker image.

I have limited experience with Docker, but if it works I'll be happy to share it.

### PR DESCRIPTION
**Pull request by suda**
Hello! I based this work on the [`rust-wasm`](https://github.com/Joystream/docker-files/blob/master/rust-wasm/Dockerfile) Dockerfile and thanks to @mnaamani suggestion of using Rustup 1.34.0 got it building. To build it on your own, run:

```
$ docker build .
```

I would also suggest creating Joystream's Docker Hub account: https://hub.docker.com/u/joystream

### CODE REVIEW

**Comment by mnaamani** [comment]
Thanks for this contribution @suda 
Will test it out.

**Comment by mnaamani** [comment]
So after I successfully built:

```

**Comment by mnaamani** [comment]
So I'm curios, in docker hub would we be publishing the image `Dockerfile` or can we actually publish the built image "49b62b70a00b" ?

**Comment by suda** [comment]
Once you'd have the Joystream's Docker Hub account, when building you'd tag it:
```
```

**Pull request merged**
